package Finals;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;



public class Final_Project extends javax.swing.JFrame {


    
   
    public Final_Project() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Userfield = new javax.swing.JTextField();
        Passwordfield = new javax.swing.JPasswordField();
        Logintxt = new javax.swing.JLabel();
        Loginbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 11, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Userfield.setBackground(new java.awt.Color(204, 204, 204));
        Userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserfieldActionPerformed(evt);
            }
        });
        jPanel1.add(Userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 271, 46));

        Passwordfield.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 271, 46));

        Logintxt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Logintxt.setForeground(new java.awt.Color(255, 255, 255));
        Logintxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logintxt.setText("Welcome to BookLine! ");
        jPanel1.add(Logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        Loginbtn.setBackground(new java.awt.Color(2, 19, 115));
        Loginbtn.setForeground(new java.awt.Color(153, 255, 153));
        Loginbtn.setText("Login");
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 271, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\elizh\\Downloads\\books.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 560, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserfieldActionPerformed

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        String user = Userfield.getText();
        String pass = Passwordfield.getText();
        int key = 3;
        
        String encryptedPass = " ";
        for (int i = 0; i < pass.length(); i++){
            char ch = pass.charAt(i);
            encryptedPass += (char)(ch+key);
        }
        
        if (user.equalsIgnoreCase("admin")&& pass.equalsIgnoreCase("admin123")){
          
        dashboard dash =new dashboard();
        dash.setVisible(true);
        dispose();
        try {
            FileWriter Writer = new FileWriter ("C:\\Users\\elizh\\OneDrive\\Desktop\\FINAL PROJECT PROG.txt");
            Writer.write(user + "," + encryptedPass + "\n");
            Writer.close();
        }catch (IOException e){
            System.out.println("ERROR");
            e.printStackTrace();
        }
        } else {
            JOptionPane.showMessageDialog(null, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginbtnActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final_Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn;
    private javax.swing.JLabel Logintxt;
    private javax.swing.JPasswordField Passwordfield;
    private javax.swing.JTextField Userfield;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}